### ISSUE TITLE
kgdoom crashes

### ISSUE THREAD

**Issue by teogorghin** [gdkchan/Ryujinx#28]
Hello! A homebrew game, kgdoom crashes when I try to run it.
Here is the game:
https://github.com/kgsws/kgdoom

**Comment by gdkchan** [comment]
It doesn't work because it requires the wad file to be sent over the network, and uses the bsd service for that. There are currently no plans to implement that since its too much work for little gain. Eventually someone will port the doom engine and run wads from the sd card since this is now possible and makes more sense.

**Comment by roblabla** [comment]
I'm implementing sdcard support to libtransistor right now. Will fix up kgdoom to use SDcard for wads then.

**Comment by gdkchan** [comment]
Its already possible to play kgdoom on latest master with the new bsd implementation, however you need to create a local server to send the wad file to the guest program on the emulator (can be done with nodejs). You may also need to edit the code since it seems to connect to a hardcoded ip address.
